### ISSUE TITLE
Problem adding Calendar folder

### ISSUE THREAD

**Issue by marcoancona** [dseph/EwsEditor#1] opened 2017-09-30 12:39 UTC
Hi, great and useful project!
I receive an error while trying to add the Calendar as root folder:

```
Exception details:
Message: Property is not valid for this object type.
Type: Microsoft.Exchange.WebServices.Data.ServiceResponseException
Source: Microsoft.Exchange.WebServices
ErrorCode: ErrorInvalidPropertyRequest
ErrorMessage: Property is not valid for this object type.
ErrorProperties:
UnreadCount
Stack Trace:
   at Microsoft.Exchange.WebServices.Data.ServiceResponse.InternalThrowIfNecessary() in e:\EWSManagedAPI\ews-managed-api\Core\Responses\ServiceResponse.cs:line 262
   at Microsoft.Exchange.WebServices.Data.ServiceResponse.ThrowIfNecessary() in e:\EWSManagedAPI\ews-managed-api\Core\Responses\ServiceResponse.cs:line 252
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute() in e:\EWSManagedAPI\ews-managed-api\Core\Requests\MultiResponseServiceRequest.cs:line 141
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalBindToFolders(IEnumerable`1 folderIds, PropertySet propertySet, ServiceErrorHandling errorHandling) in e:\EWSManagedAPI\ews-managed-api\Core\ExchangeService.cs:line 363
   at Microsoft.Exchange.WebServices.Data.ExchangeService.BindToFolder(FolderId folderId, PropertySet propertySet) in e:\EWSManagedAPI\ews-managed-api\Core\ExchangeService.cs:line 291
   at Microsoft.Exchange.WebServices.Data.ExchangeService.BindToFolder[TFolder](FolderId folderId, PropertySet propertySet) in e:\EWSManagedAPI\ews-managed-api\Core\ExchangeService.cs:line 310
   at Microsoft.Exchange.WebServices.Data.Folder.Bind(ExchangeService service, FolderId id, PropertySet propertySet) in e:\EWSManagedAPI\ews-managed-api\Core\ServiceObjects\Folders\Folder.cs:line 58
   at EWSEditor.Forms.FolderTreeForm.AddRootFolderToTreeView(ExchangeService service, EwsEditorAppSettings oAppSettings, FolderId folderId, TreeNode parent) in e:\msft tools\ewseditor\EWSEditor\Forms\FolderTreeForm.cs:line 1621
   at EWSEditor.Forms.FolderTreeForm.AddRootFolderToTreeView(FolderId folderId, TreeNode parent) in e:\msft tools\ewseditor\EWSEditor\Forms\FolderTreeForm.cs:line 1616
   at EWSEditor.Forms.FolderTreeForm.AddRootFolderMenu_Click(Object sender, EventArgs e) in e:\msft tools\ewseditor\EWSEditor\Forms\FolderTreeForm.cs:line 1109
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by dseph** [comment] 2019-11-28 00:17
This could be caused by several reasons. One is the EWS Schema or EWS version needed for the call being made.  EWSEditor does not check to see if the call being made would work for whatever call is being made - this is by design since EWSEditor was made to explore the API... which includes seeing errors for calls which would fail.  There could have been something else going on.  I'm going to close this due to the age.  If it still happens then please start a new discussion and share the request and repro steps.  Thank you.  Dan

**Closed as completed by dseph** 2019-11-28 00:17 UTC
